---
yum_flags: " "
lokkit_flags: " "
# change following line to point to an EPEL mirror closeby to your region
epel_release_url: http://mirror.ufs.ac.za/fedora-epel/6/x86_64/
epel_release_name: epel-release-6-8.noarch.rpm
# This contains the actual name of the iptables command which differs from distro to distro.
iptables_command: iptables
iptables_package: iptables
# openldap stuff
ldap_packages:
  - openldap
  - openldap-servers
  - openldap-clients
ldap_service: slapd
base_packages:
  - python-simplejson
  - libselinux-python
  - iptables
  - mlocate
  - initscripts
  - chkconfig
  - system-config-services
  - openssh-clients
  - which
  - yum-priorities
  - yum-protectbase
  - vim-minimal
