---
yum_flags: " "
lokkit_flags: " "
epel_release_url: http://fedora.mirror.ac.za/epel/6/x86_64/
epel_release_name: epel-release-6-8.noarch.rpm
umd_release_url:
  2: http://repository.egi.eu/sw/production/umd/2/sl6/x86_64/base/umd-release-2.0.0-1.el6.noarch.rpm
  3: http://repository.egi.eu/sw/production/umd/3/sl6/x86_64/base/umd-release-3.0.0-1.el6.noarch.rpm
# name of the java 6 and 7 packages
java6_name: java-1.6.0-openjdk
java7_name: java-1.7.0-openjdk
