---
yum_flags: " "
lokkit_flags: " "
epel_release_url: http://fedora.mirror.ac.za/epel/6/x86_64/
epel_release_name: epel-release-6-8.noarch.rpmbase_packages:
  - python-simplejson
  - libselinux-python
  - iptables
  - mlocate
  - initscripts
  - chkconfig
  - system-config-services
  - openssh-clients
  - which
#umd_major_release: "3"
#umd_release_url:
#  6.3: 'http://repository.egi.eu/sw/production/umd/3/sl6/x86_64/base/umd-release-3.0.0-1.el6.noarch.rpm'
#  Carbon: 'http://repository.egi.eu/sw/production/umd/3/sl6/x86_64/base/umd-release-3.0.0-1.el6.noarch.rpm'
