---
voname: sagrid.ac.za
dbtype: mysql
dbauser: root
mysql_old_root_password: 91101001adm4mysql
dbapwd: aCxwcUjIizry2nMf-U9OIs8GdnDmqnKU
dbusername: vomsadmin
dbpassword: cpbYOaAA4hv4PKCwzGZCu_OFVLbMqccv
coreport: 15000
smtphost: localhost
mailfrom: voms-admin@voms-stage.sagrid.ac.za
voadmindn: "/C=IT/O=INFN/OU=Personal Certificate/L=ZA-MERAKA/CN=Bruce Becker"
voadminca: "/C=IT/O=INFN/CN=INFN CA"
voadminemail: bbecker@csir.co.za
