---
# vars file for roles/cvmfs
prerequisites:
  - patch
  - cmake
  - zlib1g-dev
  - "linux-headers-{{ ansible_kernel }}"
  - build-essential
  - libattr1-dev
  - libssl-dev
  - uuid
  - uuid-dev
  - libfuse-dev
  - python-dev
  - unzip
  - autofs
  - attr
  - vim
