---
# Works in 2.0
# - name: download the CVMFS package (src)
#   unarchive:
#     src: https://ecsft.cern.ch/dist/cvmfs/cvmfs-2.1.20/cvmfs-2.1.20.tar.gz
#     dest: /tmp/cvmfs-2.1.20
#     copy: no
#   tags:
#     - cvmfs
#     - repos`
#   when: { ansible_os_family == 'Debian'}
- name: ensure that cvmfs user is present
  user:
    name: cvmfs
    state: present
  become: true

- name: Do we even need CVMFS ?
  stat:
    path: /usr/bin/cvmfs2
  register: cvmfs_present

- name: cvmfs stat
  debug:
    msg: "{{ cvmfs_present.stat.xgrp }}"

- name: Install prerequisites
  apt:
    name: "{{ item }}"
    state: present
  with_items: prerequisites
  become: true

- name: download tarball
  get_url:
    url: https://ecsft.cern.ch/dist/cvmfs/cvmfs-2.1.20/cvmfs-2.1.20.tar.gz
    dest: /tmp/cvmfs-2.1.20.tar.gz
  tags:
    - cvmfs
  when: cvmfs_present.stat.xgrp != True


- name: check that the untar dir is there
  file:
    path: /tmp/cvmfs/
    state: directory
  when: cvmfs_present.stat.xgrp != True


- name: unpack the CVMFS package (src)
  unarchive:
   src: /tmp/cvmfs-2.1.20.tar.gz
   dest: /tmp/cvmfs/
   copy: no
   creates: /tmp/cvmfs/cvmfs-2.1.20
  tags:
   - cvmfs
  when: cvmfs_present.stat.xgrp != True


- name: check that build dir is there
  file:
    path: /tmp/cvmfs/cvmfs-2.1.20/build
    state: directory
  when: cvmfs_present.stat.xgrp != True

- name: Generate buldfiles
  command: cmake ../ -G"Unix Makefiles"
  args:
    chdir: /tmp/cvmfs/cvmfs-2.1.20/build
    creates: /tmp/cvmfs/cvmfs-2.1.20/build/Makefile
  tags:
    - cvmfs
    - install
  when: cvmfs_present.stat.xgrp != True

- name: build CVMFS
  command: nice -n20 make -j2
  args:
    chdir: /tmp/cvmfs/cvmfs-2.1.20/build
    creates: /tmp/cvmfs/cvmfs-2.1.20/build/cvmfs/cvmfs2
  tags:
    - cvmfs
    - install
  register: makeoutput
  when: cvmfs_present.stat.xgrp != True

- name: install CVMFS
  become: true
  command: make install
  args:
    chdir: /tmp/cvmfs/cvmfs-2.1.20
  tags:
    - cvmfs
    - install
  when: cvmfs_present.stat.xgrp != True

- name: copy over the local config files
  become: true
  copy: src=etc/cvmfs/{{ item }} dest=/etc/cvmfs/{{ item }}
  with_items:
    - default.local
    - keys/apprepo.sagrid.ac.za.pub
    - config.d/apprepo.sagrid.ac.za.conf
    - keys/devrepo.sagrid.ac.za.pub
    - config.d/devrepo.sagrid.ac.za.conf
    - keys/fastrepo.sagrid.ac.za.pub
    - config.d/fastrepo.sagrid.ac.za.conf
  tags:
    - cvmfs
    - config
  when: cvmfs_present.stat.xgrp != True

- name: add the CVMFS master
  copy:
    src: etc/auto.master
    dest: /etc/auto.master
    mode: u=rw,g=r,o=r
  become: true


- name: ensure that autofs is running
  become: true
  service:
    name: autofs
    state: started
  tags:
    - cvmfs

- name: check that the repo is mounted
  stat: "path=/cvmfs/{{ item }}"
  with_items: "{{ repos }}"
  register: p

- debug: msg="Path exists and is a directory"
  when: p.stat.isdir is defined and p.stat.isdir
