---
- name: ensure that the ROOT directory exists
  become: true
  file:
    path: "{{ tomcat6_webapps}}/ROOT"
    state: directory
    owner: "{{ tomcat6_user }}"
    group: "{{ tomcat6_user }}"
    mode: 0644
- name: Push the templates
  become: true
  template:
    src: "var/lib/tomcat6/webapps/ROOT/{{ item }}.j2"
    dest: "{{ tomcat6_webapps }}/ROOT/{{ item }}"
    owner: "{{ tomcat6_user }}"
    group: "{{ tomcat6_user }}"
  with_items:
    - about.jsp
    - documentation.jsp
    - generalError.jsp
    - home.jsp
    - login.jsp
    - registrationError.jsp
    - userAdmin.jsp
    - userReject.jsp
  notify:
    - restart tomcat
