- name: Add configuration for dteam VO
  template:
    src: files/opt/glite/yaim/etc/siteinfo/vo.d/dteam.j2
    dest: /opt/glite/yaim/etc/siteinfo/vo.d/dteam
    owner: root
    group: root
    mode: 0644
  when: "'dteam' in {{ vos }}"
