- name: Add configuration for see VO
  action: template src=templates/opt/glite/yaim/etc/siteinfo/vo.d/see.j2 dest=/opt/glite/yaim/etc/siteinfo/vo.d/see owner=root group=root mode=0644
  only_if: "'see' in ${vos}"
