---
- name: Download epel-release package
  get_url: url={{ epel_release_url }}/{{ epel_release_name }} dest=/tmp/{{ epel_release_name }} mode=0644
  tags:
    - repos
    - EPEL
    - download

- name: Install epel-release package
  action: command yum localinstall -y {{ yum_flags }} /tmp/{{ epel_release_name }} creates=/etc/yum.repos.d/epel.repo
  sudo: true
  sudo_user: root
  tags:
    - repos
    - EPEL
    - install
    
#- name: change the repos to use the local ones
#  action: copy src=files/etc/yum.repos.d/epel.repo     

- name: Download EGI trustanchors release package
  action: get_url url={{ igtf_repo_url }}/{{ igtf_release_name }} dest=/tmp/{{ igtf_release_name }}
# should have a when file state==abset here
  tags: 
    - repos
    - IGTF
    - download

- name: Ensure that the repo is properly configured for yum
  get_url: url=http://repository.egi.eu/sw/production/cas/1/current/repo-files/egi-trustanchors.repo dest=/etc/yum.repos.d/egi-trustanchors.repo
  sudo: True
  tags:
    - repos
    - IGTF
    - download
  
- name: Install EGI trustanchors release package
  yum: name=/tmp/{{ igtf_release_name }} state=present
  sudo: true
  sudo_user: root
  tags: 
    - repos
    - IGTF
    - install
    
#- name: Install yum-plugin-replace package
#  action: yum name=yum-plugin-replace state=latest
#  sudo: true
#  sudo_user: root
#  tags: 
#    - yumconfig

- name: Install yum-priorities package
  action: command yum install -y ${yum_flags} yum-priorities
  sudo: true
  sudo_user: root
  tags: 
    - yumconfig

- name: Install yum-protectbase package
  action: yum name=yum-protectbase state=latest
  sudo: true
  sudo_user: root
  tags: 
    - yumconfig
