- name: certs in userspace
  action: file src=/etc/grid-security/hostcert.pem dest=/etc/grid-security/fts3hostcert.pem owner=fts3 group=fts mode=0644
  sudo: True
  tags:
    - configure
    
- name: keys in userspace
  action: file src=/etc/grid-security/hostkey.pem dest=/etc/grid-security/fts3hostkey.pem owner=fts3 group=fts mode=0400
  sudo: True
  tags:
    - configure

- name: configuration - set IP
  lineinfile: dest=/etc/fts3/fts3config regexp=^IP= line=IP={{ IP }}
  sudo: True
  tags:
    - configure

- name: configuration - DbUserName
  lineinfile: dest=/etc/fts3/fts3config regexp=^DbUserName= line=DbUserName={{ DbUserName }}
  sudo: True
  tags:
    - configure

- name: configuration - DbPassword
  lineinfile: dest=/etc/fts3/fts3config regexp=^DbPassword= line=DbPassword={{ DbPassword }}
  sudo: True
  tags:
    - configure

- name: configuration - Alias
  lineinfile: dest=/etc/fts3/fts3config regexp=^Alias= line=Alias={{ Alias }}
  sudo: True
  tags:
    - configure
    
- name: configuration - Infosys
  lineinfile: dest=/etc/fts3/fts3config regexp=^Infosys= line=Infosys={{ Infosys }}
  sudo: True
  tags:
    - configure
    
- name: configuration - Site Name
  lineinfile: dest=/etc/fts3/fts3config regexp=^SiteName= line=SiteName={{ SiteName }}
  sudo: True
  tags:
    - configure

- name: configuration - MonitoringMessaging
  lineinfile: dest=/etc/fts3/fts3config regexp=^MonitoringMessaging= line=MonitoringMessaging={{ MonitoringMessaging }}
  sudo: True
  tags:
    - configure
- name: configuration - Connect String
  lineinfile: dest=/etc/fts3/fts3config regexp=^DbConnectString= line=DbConnectString={{ DbConnectString }}
  sudo: True
  tags:
    - configure

- name: configuration - Profiling
  lineinfile: dest=/etc/fts3/fts3config regexp=^Profiling= line=Profiling={{ Profiling }}
  sudo: True
  tags:
    - configure
- name: start mysql
  action: service name=mysql
  
- name: Log dir
  copy: src=etc/httpd/conf.d/fts3logs.conf dest=/etc/httpd/conf.d/fts3logs.conf
  sudo: True
  tags:
    - configure
  
- name: Configure SSL Certificate File
  lineinfile: dest=/etc/httpd/conf.d/ssl.conf regexp=^SSLCertificateFile line=SSLCertificateFile /etc/grid-security/hostcert.pem
  sudo: True
  tags:
    - configure

- name: Configure SSL Key file
  lineinfile: dest=/etc/httpd/conf.d/ssl.conf regexp=^SSLCertificateKeyFile line=SSLCertificateKeyFile /etc/grid-security/hostkey.pem
  sudo: True
  tags:
    - configure
    
- name: Configure CA path
  lineinfile: dest=/etc/httpd/conf.d/ssl.conf regexp=^SSLCACertificatePath line=SSLCACertificatePath /etc/grid-security/certificates
  sudo: True
  tags:
    - configure

- name: require SSL

