- name: Install FTS packages
  sudo: True
  yum: name={{ item }} state=present
  with_items: 
    - fts-server
    - fts-client
    - fts-monitoring
    - fts-mysql
    - mysql-server
    - MySQL-python
    - httpd
  tags: 
    - packages
    - install
      
- name: start mysql
  sudo: True
  action: service name=mysqld state=started
  tags:
    - start

- name: add mysql user and add priveliges
  sudo: True
  mysql_user: name={{ DbUserName }} password={{ DbPassword }} priv=*.*:ALL state=present
  tags:
    - configure

- name: create the FTS database
  mysql_db: name=fts3 state=present
  sudo: True
  tags:
    - configure

- name: import db
  sudo: True
  raw:  'mysql -u root fts3 < /usr/share/fts-mysql/mysql-schema.sql'
  tags: 
    - configure
