- name: Create /etc/grid-security directory
  file:
    path: /etc/grid-security/certificates
    owner: root
    group: root
    mode: 775
    state: directory
    force: true
  tags:
    - certificates

- name: Copy host x509 certificate into /etc/grid-security
  copy:
    src: "etc/grid-security/hostcert.pem-{{ ansible_fqdn }}"
    dest: /etc/grid-security/hostcert.pem
    owner: root
    group: root
    mode: 0644
    force: true
  when: "(hostvars['{{ inventory_hostname }}'].needs_certificate == 'true') and (needs_certificate is defined)"
  tags:
    - certificates

- name: Copy host x509 private key into /etc/grid-security
  copy:
    src: "etc/grid-security/hostkey.pem-{{ ansible_fqdn }}"
    dest: /etc/grid-security/hostkey.pem
    owner: root
    group: root
    mode: 0400
  when: (hostvars['{{ inventory_hostname }}'].needs_certificate == 'true') and (needs_certificate is defined)
  tags:
    - certificates

- name: Copy over CA certs by hand
  copy:
    src: "etc/grid-security/certificates/{{ item }}"
    dest: "/etc/grid-security/certificates/{{ item }}"
  with_items:
    - 16b5ebeb.0
    - 16b5ebeb.crl_url
    - 16b5ebeb.r0
    - 16b5ebeb.signing_policy
    - 8c65b6c6.0
    - 8c65b6c6.crl_url
    - 8c65b6c6.r0
    - 8c65b6c6.signing_policy
    - AAROC.0
    - AAROC.crl_url
    - AAROC.r0
    - AAROC.signing_policy
  tags:
    - certificates

- name: Add SAGrid VO certs and LSC files
  copy:
    src: etc/grid-security/vomsdir
    dest: /etc/grid-security/
    owner: root
    group: root
