---
- name: check that the glassfish directory exists and is writeable
  sudo: true
  file: name=/opt/glassfish state=directory owner=liferayadmin group=liferayadmin

- name: check if glassfish has already been installed
  sudo: true
  sudo_user: liferayadmin
  stat: path=/opt/glassfish/glassfish3/bin/asadmin
  register: asadmin_stat

# only run further checks if necessary
- name: check whether glassfish tarball is downloaded
  sudo: true
  sudo_user: liferayadmin
  stat: path=/home/liferayadmin/glassfish-3.1.2.2.zip
  register: glassfish_stat
  when: asadmin_stat.stat.exists != True


- name: What is  the glassfish stat ?
  debug: msg="{{ glassfish_stat.stat.exists }}"

- name: download glassfish
  sudo: true
  sudo_user: liferayadmin
  get_url: url=http://download.java.net/glassfish/3.1.2.2/release/glassfish-3.1.2.2.zip dest=/home/liferayadmin/glassfish-3.1.2.2.zip
  when: glassfish_stat.stat.exists != True

- name: extract the zip
  sudo: true
  sudo_user: liferayadmin
#  unarchive: src=/home/liferayadmin/glassfish-3.1.2.2.zip  dest=/opt/glassfish copy=no creates=/opt/glassfish/glassfish3/glassfish/bin/asadmin
  command: /usr/bin/unzip -d /opt/glassfish glassfish-3.1.2.2.zip creates=/opt/glassfish/glassfish3/
  when: asadmin_stat.stat.exists == false

# - name: check that the domain hasn't been created
#   sudo: true
#   sudo_user: liferayadmin
#   shell: ./asadmin list-domains chdir=/opt/glassfish/glassfish3/bin/
#   register: domains

# - name: start the server
#   sudo: true
#   sudo_user: liferayadmin
#   shell: ./asadmin create-domain --user=liferayadmin  --nopassword liferay  chdir=/opt/glassfish/glassfish3/bin/
#   when: domains.stdout | match("liferay")

#- name: Configure jvm parameters
#  copy:
