---
#wms_ports:
#  - {port: 2170, service: 'standard BDII'}
#  - {port: 2811, service: 'GridFTP control channel'}
#  - {port: 7443, service: 'Apache GridSite web service (SOAP over https)'}
#  - {port: 9003, service: 'LB WS client queries'}
#  - {port: 9618, service: 'condor_collector'}
wms_ports:
  - 2170
  - 2811
  - 7443
  - 9003
  - 9618
