---
# EPEL yum repository.
- name: Download UMD 3 repo.
  get_url: url=http://repository.egi.eu/sw/production/umd/3/sl6/x86_64/base/umd-release-3.0.0-1.el6.noarch.rpm dest=/tmp/umd-release.rpm
  when: ansible_hostname.find("nagios") == -1
  tags:
    - repos
    - UMD3

- name: Download UMD 2 repo
  get_url: http://repository.egi.eu/sw/production/umd/2/sl5/x86_64/base/umd-release-2.0.0-1.el5.noarch.rpm dest=/tmp/umd-release.rpm 
  when: ansible_hostname.find("nagios") != -1
  tags:
    - repos
    - UMD2
    
- name: add EGI GPG key to RPM
  sudo: True
  sudo_user: root
  action: rpm_key state=present key=http://repository.egi.eu/sw/production/umd/UMD-RPM-PGP-KEY
  tags:  
    - repos
    - UMD

- name: Install UMD repo.
  sudo: True
  sudo_user: root
  command: yum localinstall -y /tmp/umd-release.rpm
#  when: yum name=umd-release state==absent
  tags:
    - repos
    - UMD
