---
- name: Copy apache ajp proxy cofiguration (RedHat)
  copy: src=etc/proxy_ajp.conf dest=/etc/httpd/conf.d/proxy_ajp.conf
  when: ansible_os_family == "RedHat"

- name: Configure Virtualhost (RedHat)
  template: src=etc/virtualhost.conf.j2 dest=/etc/httpd/conf.d/virtualhost.conf
  when: ansible_os_family == "RedHat"

- name: Check that Proxy AJP module is commented
  lineinfile: dest=/etc/httpd/conf/httpd.conf regexp='^LoadModule proxy_ajp_module modules/mod_proxy_ajp.so' line='#LoadModule proxy_ajp_module modules/mod_proxy_ajp.so' backrefs=yes
  when: ansible_os_family == "RedHat"
  notify: restart httpd

- name: KeepAlive On
  lineinfile: dest=/etc/httpd/conf/httpd.conf regexp='^KeepAlive Off' line='KeepAlive On' state=present backrefs=yes
  when: ansible_os_family == "RedHat"
  notify: restart httpd

- name: Ensure that httpd starts at boot
  command: /sbin/chkconfig httpd on
  when: ansible_os_family == "RedHat"
