---
- name: Add Liferay user
  sudo: true
  user: name=liferayadmin group=liferayadmin state=present
  tags:
    - prep

- name: disable selinux
  sudo: true
  selinux: state=disabled
  notify: reboot
  tags:
    - prep

- name: Ensure that the hostname is in /etc/hosts
  lineinfile:
    dest=/etc/hosts
    line="{{ ansible_eth0_ipv4 }} {{ ansible_fqdn }} {{ ansible_hostname }}"
    state=present
  tags:
    - prep

- name: Update the open files limit
  lineinfile:
    dest=/etc/sysctl.conf
    regexp='^fs.file-max='
    line="fs.file-max={{ file_max_open }}"
  tags:
    - prep
