---
# Certificate information
#  which CA issued the certificate
cert_CA: comodo
# this is the list of the root and intermediate certificates of the CA
# should probably give these keys names...
cert_CA_certificates:
  - COMODORSADomainValidationSecureServerCA.crt
  - AddTrustExternalCARoot.crt
  - COMODORSAAddTrustCA.crt
# institute metadata
site_name: DevOpsCatch-All
host_institute:
  name: Eko-Konnect Dev
  url: http://www.eko-konnect.org.ng

# LDAP variables
server_country: NG
server_state: Lagos
server_location: Lagos
server_organization: ngREN
server_organization_unit: eko-konnect
organisation:
  name: Eko-konnect
  logo:
# ldap_server:
# sgw_admin: brucellino@gmail.com
mail_contact: secretariat@eko-konnect.org.ng


# IDP variables. these are specifically related to the IdPOpen Web front end.
idp:
  name: First eko-konnect DevOps idp.
  admin_user: NOC
  admin_email: noc@eko-konnect.org.ng
  metadata_url: https://{{ hostvars[groups['shibboleth-idps'][0]]['ansible_fqdn']}}/idp/shibboleth
  mail_server: smtp01.eko-konnect.org.ng
  header_logo:
