---
umd_major_release: 3
vos:
  - dteam
  - ops
  - sagrid
#  - eumed
#  - africacert
queues:
  - dteam
  - cert
  - shared
# See https://wiki.egi.eu/wiki/MAN01_How_to_publish_Site_Information
# use the site name as registered in GOCDB (use the same case)
site_name: ZA-MERAKA-DEV
# contact details
site_email: sagrid@csir.co.za
site_security_email: csirt@sanren.ac.za
site_support_email: za-meraka-ops@lists.sagrid.ac.za
# location
site_latitude: -25.75593
site_longitude: 28.27921
site_description: "Meraka Institute - core grid services"
site_other_grid: "EGI"
site_bdii_host: "site-bdii.c4.csir.co.za"
site_location: "Pretoria, South Africa"
site_website: "http://www.csir.co.za/meraka"
site_domain: c4.csir.co.za

# services at the site - these should be taken from the inventory in a perfect world
# However, the inventory only defines groups and roles of machines... not
# individual hosts
bdii_host: top-bdii.c4.csir.co.za
apel_mysql_host: ce01-node001.c4.csir.co.za
px_host: myproxy.cern.ch
wms_host: wms.c4.csir.co.za
argus_status: no
# TODO - new LFC has to be deployed here at Meraka | BB 10/13
lfc_host: devslngrd002.uct.ac.za

ce_host: ce01-node001.c4.csir.co.za
# Replace the following specs with your own
ce_cpu_model: Opteron
ce_cpu_vendor: AMD
ce_cpu_speed: 2600
ce_os: ScientificSL
ce_os_release: 6.4
ce_os_version: Final
ce_os_arch: x86_64
ce_minphysmem: 2048
ce_minvirtmem: 6144
ce_physcpu: 1
ce_logcpu:
ce_smpsize: 1
ce_si00: 2105
ce_sf00: 2601
ce_outboundip: "TRUE"
ce_inboundip: "FALSE"
ce_runtimeenv:
  - NGI_ZA
  - SAGrid
  - C4 Production cluster
  - ZA-MERAKA
ce_otherdescr: Cores=1.0,Benchmark=8.42-HEP-SPEC06
batch_server: ce01-node001.c4.csir.co.za
job_manager: lcgpbs
ce_batch_sys: torque
batch_log_dir: /var/torque
batch_version: torque-2.5.7

# vars for service: emi_dpm_mysql
dpm_host: se.c4.csir.co.za
dpmmgr: { uid: 400, gid: 4000 }
dpm_filesystems: "sitename_dpm:$DPM_HOST:/storage"
dpm_db:   { user: dpmmgr,  pass: redacted }
dpm_info: { user: dpminfo, pass: redacted }

# vars for service: BDII_site
bdii_regions:
- name: CREAM
  # we should get this from the inventory
  endpoint: ldap://ce01-node001.c4.csir.co.za:2170/mds-vo-name=resource,o=grid
- name: SITE_BDII
  endpoint: ldap://site-bdii.c4.csir.co.za:2170/mds-vo-name=resource,o=grid
#- name: SE
#  endpoint: ldap://se01.localdomain:2170/mds-vo-name=resource,o=grid
#- name: LFC
#  endpoint: ldap://lfc01.localdomain:2170/mds-vo-name=resource,o=grid
#- name: PX
#  endpoint: ldap://myproxy01.localdomain:2170/mds-vo-name=resource,o=grid

se_list:
  - se01.localdomain

se_mount_info_list: none
se_gridftp_logfile: /var/log/dpm-gsiftp/dpm-gsiftp.log

sandboxdir_on_ce: /var/cream_sandbox
sandboxdir_on_wn: /cream_sandbox
