- name: run yaim
  action: shell sudo -i rm -f ${batch_log_dir}/mom_priv/config
  notify:
    - really run yaim
- name: really run yaim
  action: shell sudo -i ${yaim_path}/bin/yaim -c -s ${yaim_conf_dir}/site-info.def -n MPI_WN -n WN -n TORQUE_client
  notify:
    - fix mom config 1
    - fix mom config 2
    - fix mom config 3
    - fix mom config 4
- name: fix mom config 1
  action: shell echo \\$usecp\ ${ce_host}:/home\ /home >> ${batch_log_dir}/mom_priv/config 
  notify:
    - reload pbs_mom
- name: fix mom config 2
  action: shell echo \\$usecp\ ${ce_host}:/var/cream_sandbox\ /cream_sandbox >> ${batch_log_dir}/mom_priv/config
  notify:
    - reload pbs_mom
- name: fix mom config 3
  action: shell echo \\$tmpdir\ /var/torque/spool/tmpdir >> ${batch_log_dir}/mom_priv/config
  only_if: "'${ansible_lsb.major_release}' == '5'"
  notify:
    - reload pbs_mom
- name: fix mom config 4
  action: shell echo \\$tmpdir\ /var/lib/torque/spool/tmpdir >> ${batch_log_dir}/mom_priv/config 
  notify:
    - reload pbs_mom
  only_if: "'${ansible_lsb.major_release}' == '6'"
- name: reload pbs_mom
  action: service name=pbs_mom state=reloaded
- name: restart munge
  action: service name=munge state=restarted
