- name: run yaim
  action: shell sudo -i ${yaim_path}/bin/yaim -c -s ${yaim_conf_dir}/site-info.def -n BDII_site
  notify:
    - run post yaim 1
- name: run post yaim 1
  action: copy src=files/var/lib/bdii/gip/ldif/patch.ldif.rb dest=/var/lib/bdii/gip/ldif/patch.ldif.rb owner=root group=root mode=0755
  notify: 
    - run post yaim 2
- name: run post yaim 2
  action: command ruby patch.ldif.rb chdir=/var/lib/bdii/gip/ldif
  notify: 
    - run post yaim 3
- name: run post yaim 3
  action: command rm -f patch.ldif.rb chdir=/var/lib/bdii/gip/ldif
  notify: 
    - restart bdii
- name: restart bdii
  action: service name=bdii state=restarted
