galaxy_info:
  author: Bruce Becker
  description: A role to perform functional tests on a site-bdii
  company: CSIR Meraka Institute
  license: Apache 2.0
  min_ansible_version: 2.0
  platforms:
    - name: EL
        versions:
          - 6
  galaxy_tags:
    - testing
    - grid
    - ldap
    - site-bdii
