- name: Create munge key
  become_user: munge
  command: /usr/sbin/create-munge-key
    args:
  creates: /etc/munge/munge.key
  tags:
    - munge

- name: Fix munge permissions if necessary
  file:
    path: /etc/munge/munge.key
    owner: munge
    group: munge
  tags:
    - munge

- name: Pull in munge key
# we have to use a command here instead of file because the ansible user cannot gain access to the file (permissions)
  command: 'cp /etc/munge/munge.key munge.key'
  tags:
    - munge

- name: Start munge
  service:
    name: munge
    enabled: on
    state: started
