---
- hosts: all
  tasks: 
  - name: test bash
    script: ./config/files/test-bashpocalypse.sh
    register: result
    ignore_errors: True

  - yum: name=bash state=latest
    when: result.stdout | search("vulnerable")
    notify: check
   
  - name: update the security repo if needed
    lineinfile: dest=/etc/yum.repos.d/sl.repo regexp=^baseurl= line=baseurl=http://ftp.scientificlinux.org/linux/scientific/6x/x86_64/updates/security/
    when: result.stdout | search("vulnerable")

  - name: update bash after repo change
    yum: name=bash state=latest
    notify: check
    when: result.stdout | search("vulnerable")
  
  handlers:
  - name: check
    script: ./config/files/test-bashpocalypse.sh
    register: result
    ignore_errors: True
