# playbooks for a normal site core services
---
- name: Apply the common role to all hosts
  hosts: core-services
  user: ansible
  become: true
  pre_tasks:
    - slack:
        domain: africa-arabia-roc.slack.com
        token: "{{ slack_token }}"
        msg: "Starting Core Services Deployment at  {{ site_name }}"
        channel: "#devopssite"
        username: "Ansible on {{ inventory_hostname }}"
        link_names: 1
        parse: 'full'
  post_tasks:
    - slack:
        domain: africa-arabia-roc.slack.com
        token: "{{ slack_token }}"
        msg: "Ready for Core Services Configuration at {{ site_name }}"
        channel: "#devopssite"
        username: "Ansible on {{ inventory_hostname }}"
        link_names: 1
        parse: 'full'
  roles:
    - common
  vars_files:
    - roles/common/vars/distros/{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml
    - roles/common/vars/middleware/IGTF.yml
    - group_vars/passwords-{{ site_name }}.yml

- name: Deploy top-bdiis
  hosts: top-bdiis
  user: ansible
  become: true
  roles:
    - { role: UMD-role, tags: "umd"}
    - { role: top-bdii, tags: "top-bdii"}
    - { role: yaim, tags: yaim}
  vars_files:
    - group_vars/passwords-{{ site_name }}.yml
  pre_tasks:
    - slack:
        domain: africa-arabia-roc.slack.com
        token: "{{ slack_token }}"
        msg: "Starting Top-BDII deploys at {{ site_name }}"
        channel: "#devopssite"
        username: "Ansible on {{ inventory_hostname }}"
        link_names: 1
        parse: 'full'
  post_tasks:
    - slack:
        domain: africa-arabia-roc.slack.com
        token: "{{ slack_token }}"
        msg: "Just finished Yaim at {{ site_name }} on {{ ansible_fqdn }}"
        channel: "#devopssite"
        username: "Ansible on {{ inventory_hostname }}"
        link_names: 1
        parse: 'full'
