# playbooks for a normal site core services
---
- name: Apply the common role to all hosts
  hosts: core-services
  user: ansible
  sudo: true
  pre_tasks:
    - action:
        module: slack
        domain: africa-arabia-roc.slack.com
        token: "{{ slack_token }}"
        msg: "Starting Core Services Deployment at  {{ site_name }}"
        channel: "#devopssite"
        username: "Ansible on {{ inventory_hostname }}"
        link_names: 1
        parse: 'full'
  post_tasks:
    - action:
        module: slack
        domain: africa-arabia-roc.slack.com
        token: "{{ slack_token }}"
        msg: "Ready for Core Services Configuration at {{ site_name }}"
        channel: "#devopssite"
        username: "Ansible on {{ inventory_hostname }}"
        link_names: 1
        parse: 'full'
  roles:
    - common
  vars_files:
    - roles/common/vars/distros/{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml
    - roles/common/vars/middleware/IGTF.yml
    - group_vars/passwords-{{ site_name }}.yml

- name: Deploy top-bdiis
  hosts: top-bdiis
  user: ansible
  sudo: true
  roles:
    - umd
    - top-bdii
    - yaim
  vars_files:
    - group_vars/passwords-{{ site_name }}.yml
  pre_tasks:
    - action:
        module: slack
        domain: africa-arabia-roc.slack.com
        token: "{{ slack_token }}"
        msg: "Starting Top-BDII deploys at {{ site_name }}"
        channel: "#devopssite"
        username: "Ansible on {{ inventory_hostname }}"
        link_names: 1
        parse: 'full'
  post_tasks:
    - action:
        module: slack
        domain: africa-arabia-roc.slack.com
        token: "{{ slack_token }}"
        msg: "Just finished Yaim at {{ site_name }} on {{ ansible_fqdn }}"
        channel: "#devopssite"
        username: "Ansible on {{ inventory_hostname }}"
        link_names: 1
        parse: 'full'

- name: Deploy WMS
  hosts: wms-servers
  user: ansible
  sudo: true
  roles:
    - certificates
    - umd
    - wms
    - yaim
  vars_files:
    - group_vars/passwords-{{ site_name }}.yml
  pre_tasks:
    - action:
        module: slack
        domain: africa-arabia-roc.slack.com
        token: "{{ slack_token }}"
        msg: "Starting WMS deploys at {{ site_name }}"
        channel: "#devopssite"
        username: "Ansible on {{ inventory_hostname }}"
        link_names: 1
        parse: 'full'
  post_tasks:
    - action:
        module: slack
        domain: africa-arabia-roc.slack.com
        token: "{{ slack_token }}"
        msg: "Just finished Yaim at {{ site_name }} on {{ ansible_fqdn }}"
        channel: "#devopssite"
        username: "Ansible on {{ inventory_hostname }}"
        link_names: 1
        parse: 'full'

- name: Deploy SAM-NAGIOS
  hosts: ngi-nagios
  user: ansible
  sudo: true
  roles:
    - certificates
    - umd
    - sam-nagios
    - yaim
  vars_files:
    - group_vars/passwords-{{ site_name }}.yml
  pre_tasks:
    - action:
        module: slack
        domain: africa-arabia-roc.slack.com
        token: "{{ slack_token }}"
        msg: "Starting SAM-NAGIOS deploys at {{ site_name }}"
        channel: "#devopssite"
        username: "Ansible on {{ inventory_hostname }}"
        link_names: 1
        parse: 'full'
  post_tasks:
    - action:
        module: slack
        domain: africa-arabia-roc.slack.com
        token: "{{ slack_token }}"
        msg: "Just finished Yaim at {{ site_name }} on {{ ansible_fqdn }}"
        channel: "#devopssite"
        username: "Ansible on {{ inventory_hostname }}"
        link_names: 1
        parse: 'full'
