---
- name: Add new user to ldap
  hosts: ldap-server
  remote_user: ansible
  become: true
  tasks:
    - name: copy ldif over
      copy: src=files/new_user.ldif dest=/tmp/new_user.ldif
    - name: add new user
      command: ldapadd -x -w {{ root_password_clear }} -D cn={{ admin }},dc=local -H ldap:/// -f /tmp/new_user.ldif
  vars_files:
    - roles/ldap/vars/main.yml
