---
- hosts: UIs
  user: ansible
  sudo: true
  roles:
    - bootstrap
    - common
    - certificates
    - umd
    - ui
    - yaim
  vars_files:
    - roles/common/vars/distros/{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml
    - roles/common/vars/middleware/igtf.yml
    - roles/yaim/vars/main.yml
#  handlers:
#    - roles/yaim/handlers/main.yml
