---
- hosts: voms-servers
  name: VOMS plays
  become: true
  become_user: root
  roles:
    - bootstrap
    - common
    - certificates
    - umd
    - voms
  vars_files:
    - "group_vars/passwords-{{ site_name }}.yml"
    - "roles/common/vars/distros/{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
    - "roles/common/vars/middleware/igtf.yml"
