---
- hosts: wms-servers
  name: Deploy and configure WMS
  remote_user: ansible
  become: true
  pre_tasks:
    - include_vars: "{{ item }}"
      with_items:
        - "roles/common/vars/distros/{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
        - roles/common/vars/middleware/IGTF.yml
        - "group_vars/passwords-{{ site_name }}.yml"
    - name: Announce the play via Slack
      action:
        module: slack
        token: "{{ slack_token }}"
        msg: "Running WMS play on {{ inventory_hostname }} at {{ site_name }}"
        channel: "#{{ site_name | lower }}-ops"
        username: "Ansible on {{ inventory_hostname }}"
        icon_emoji: ansible
        validate_certs: false
        link_names: 1
        parse: 'full'
  roles:
#    - bootstrap
    - common
    - certificates
    - umd
    - wms
    - yaim

  handlers:
    - include: roles/common/handlers/main.yml
  post_tasks:
    - name: Announce the play outcome
      action:
          module: slack
          token: "{{ slack_token }}"
          msg: "WMS play on {{ inventory_hostname }} at {{ site_name }} finished O/ ... running tweaks..."
          channel: "#{{ site_name | lower }}-ops"
          username: "Ansible on {{ inventory_hostname }}"
          link_names: 1
          icon_emoji: ansible
          parse: 'full'
          validate_certs: false

- hosts: wms-servers
  remote_user: ansible
  tasks:
    - name: wms host name
      debug:
        msg: "WMS host name is {{ hostvars[groups['wms-servers'][0]].ansible_fqdn }}"
    - name: tweak WMS
      become: true
      template:
        src: roles/wms/templates/etc/glite-wms/glite_wms.conf.j2
        dest: /etc/glite-wms/glite_wms.conf
        owner: root
        group: root
      notify: restart-wms-wm
  handlers:
    - name: restart-wms-wm
      become: true
      command: '/etc/init.d/glite-wms-wm restart'

- hosts: wms-servers
  remote_user: ansible
  tasks:
    - include_vars: "group_vars/passwords-{{ site_name }}.yml"
    - name: announce play outcome via Slack
      slack:
        token: "{{ slack_token }}"
        msg: "WMS play on {{ inventory_hostname }} at {{ site_name }} finished O/"
        channel: "#{{ site_name | lower }}-ops"
        username: "Ansible on {{ inventory_hostname }}"
        icon_emoji: ansible
        link_names: 1
        parse: 'full'
        validate_certs: false
