---
- hosts: wms-servers
  name: WMS plays
  user: ansible
  sudo: true
  sudo_user: root
  roles:
    - common
    - certificates
    - umd
    - wms
    - yaim
  vars_files:
    - roles/common/vars/distros/{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml
    - roles/common/vars/middleware/igtf.yml
