---
# Xrootd base playbook.
# Puppet should take over after installation
- name: Prepare xrootd machines
  hosts: xrootd-servers
  roles:
    - { role: common, become: true }
    - { role: certificates, become: true }
    - { role: umd, become: true }
    - { role: xrootd, become: true }
  vars_files:
    - roles/common/vars/distros/{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml
    - roles/common/vars/middleware/IGTF.yml
