---
- name: Install emi-cream software in no cluster mode
  sudo: true
  action: yum name=emi-cream-ce state=latest
  tags:
    - CE
    - install

- name: ensure that the repos are up to date
  sudo: true
  action: yum name=* state=latest # in 2.0 you can do exclude={{ exclude_packages }}    , for now we're just going to have to work around it.

- name: Install batch system specific software
  sudo: true
  action: yum name={{ item }} state=latest
  with_items:
    - emi-torque-server
    - emi-torque-utils
    - emi-mpi
  retries: 2
  tags:
    - CE
    - install
