at  - name: Which site are we on ?
  debug: msg={{ site_name }}

- name: Create siteinfo directory
  sudo: True
  sudo_user: root
  action: file path=/opt/glite/yaim/etc/{{ site_name }}/siteinfo owner=root group=root mode=0750 state=directory
  tags:
    - yaim
- name: Create VOs subdirectory
  sudo: true
  sudo_user: root
  action: file path=/opt/glite/yaim/etc/{{ site_name }}/siteinfo/vo.d owner=root group=root mode=0770 state=directory
  tags:
    - yaim
- name: Create siteinfo/services directory and VOs subdirectory
  sudo: true
  sudo_user: root
  action: file path=/opt/glite/yaim/etc/{{ site_name }}/siteinfo/services owner=root group=root mode=0770 state=directory
  tags:
    - yaim

- name: Disable update_crl
  lineinfile:
    dest: {{ item }}
    line: config_crl
    state: absent
  with_items: *
  when: SkipCRLs == 'true' | default = 'false'
