---
- name: Which site are we on ?
  debug:
    var: site_name
  changed_when: false
  tags:
    - debug

- name: Create siteinfo directory
  file:
    path: "/opt/glite/yaim/etc/{{ site_name | default(generic) }}/siteinfo"
    owner: root
    group: root
    mode: 0750
    state: directory
  tags:
    - yaim
- name: Create VOs subdirectory
  file:
    path: "/opt/glite/yaim/etc/{{ site_name | default(generic) }}/siteinfo/vo.d"
    owner: root
    group: root
    mode: 0770
    state: directory
  tags:
    - yaim

- name: Create siteinfo/services directory and VOs subdirectory
  file:
    path: "/opt/glite/yaim/etc/{{ site_name | default(generic) }}/siteinfo/services"
    owner: root
    group: root
    mode: 0770
    state: directory
  tags:
    - yaim

- name: Ensure that the worker home directories are there
  file:
    path: "{{ user_home_prefix }}"
    state: directory
    mode: 777
  when: ("worker-nodes" in groups and ansible_hostname in groups['worker-nodes']) and ( user_home_prefix  != "")

- name: Disable update_crl
  lineinfile:
    regexp: "config_crl"
    dest: "/opt/glite/yaim/node-info.d/{{ item }}"
    state: absent
  with_fileglob:
   - /opt/glite/yaim/node-info.d/*
  when: SkipCRLs ==  'true'
  ignore_errors: true
  tags:
    - yaim
