---
galaxy_info:
  author: Bruce Becker
  description: A role to create an EMI/UMD worker node.
  company: Meraka Institute
  license: CC-BY
  min_ansible_version: 1.2
  platforms:
  - CentOS6
  categories:
  - Middleware
  - HPC
  - Grid
dependencies: []
  - worker-node
  
