- hosts: umd2
  user: ansible
  sudo: True
  vars_files:
    - vars/distros/${ansible_distribution}-${ansible_lsb.major_release}.yml
  tasks:
    - include: tasks/cas/repo.yml
    - include: tasks/epel/repo.yml
    - include: tasks/umd/repo.yml

# comment: This playbook will setup EGI-trustanchors, Epel and Umd repository files
# within /etc/yum.repos.d/ on all umd2 nodes in your setup. Make sure to update
# configurations within tasks and vars files whenever you will need to upgrade