- hosts: se-servers
  user: ansible
  sudo: True
  vars_files:
    - vars/distros/${ansible_distribution}-${ansible_lsb.major_release}.yml
    - vars/yaim.yml
  tasks:
    - include: tasks/certificates/config.yml
    - include: tasks/yaim/config_dirs.yml
    - include: tasks/yaim/vos.yml
    - include: tasks/yaim/siteinfo.yml
    - include: tasks/emi-dpm_mysql/config.yml
    - include: tasks/mysql-server/config.yml
  handlers:
    - include: handlers/emi-dpm_mysql.yml
    - include: handlers/network.yml

# vim: set filetype=yaml et ts=2 sw=2:
