# this is the task which configures the networking parameters of the head node.
# It does the following:
# 1.) enables TCP forwarding from by the head node from the worker node
# 2.) configures NFS exports and services
# 3.) Enables masquerading of the WN in the LAN
# 4.) Adds all worker nodes to the known-hosts file
# 5.) Adds known hosts to the hosts file
# not necessarily in that order
- name: Debug host network
  debug:
    var: "hostvars['{{ item }}']['ansible_default_ipv4']['address']"
  with_items: groups['worker-nodes'][0]

- name: build local network
  template: src=etc/hosts.j2 dest=/etc/hosts


# Add all the worker nodes to the list of hosts in /etc/hosts
# Their host names and addresses are added to the /etc/hosts file
#- name: Update /etc/hosts
#  template: src=etc/hosts.j2 dest=/etc/hosts

- name: Allow TCP forwarding
#  command: /bin/echo 1 > /proc/sys/net/ipv4/ip_forward
  lineinfile: dest=/proc/sys/net/ipv4/ip_forward line=1
  tags:
  - network

# Firewall configuration

- name: Enabled masquerading
  command: '{{ iptables_command }} -t nat -A POSTROUTING -o eth0 -j MASQUERADE'
  tags:
  - network
  - firewall

## Unload modules on restart and stop
##   Value: yes|no,  default: yes
## This option has to be 'yes' to get to a sane state for a firewall
## restart or stop. Only set to 'no' if there are problems unloading netfilter
## modules.
- name: "Unload modules on restart and stop"
  lineinfile: dest=/etc/sysconfig/iptables-config regexp="^#IPTABLES_MODULES_UNLOAD=" line='IPTABLES_MODULES_UNLOAD="yes"'
  notify:
  - restart iptables
  tags:
  - network
  - firewall

## Save current firewall rules on stop.
##   Value: yes|no,  default: no
## Saves all firewall rules to /etc/sysconfig/iptables if firewall gets stopped
## (e.g. on system shutdown).
- name: "Save current firewall rules on stop"
  lineinfile: dest=/etc/sysconfig/iptables-config regexp="#IPTABLES_SAVE_ON_STOP=" line='IPTABLES_SAVE_ON_STOP="yes"'
  notify:
  - restart iptables
  tags:
  - network
  - firewall

## Save current firewall rules on restart.
##   Value: yes|no,  default: no
## Saves all firewall rules to /etc/sysconfig/iptables if firewall gets
## restarted.
#IPTABLES_SAVE_ON_RESTART="yes"
- name: "Save current firewall rules on restart"
  lineinfile: dest=/etc/sysconfig/iptables-config regexp="#IPTABLES_SAVE_ON_RESTART=" line='IPTABLES_SAVE_ON_RESTART="yes"'
  notify:
  - restart iptables
  tags:
  - network
  - firewall
